[package]
name = "folco-renderer"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
twemoji = ["dep:twemoji-assets"]
jsonschema = ["dep:schemars", "folco-model/jsonschema"]
clap = ["folco-model/clap"]
tsify = ["dep:tsify", "dep:wasm-bindgen", "folco-model/tsify"]

[dependencies]
folco-model = { path = "../folco-model" }
base64 = "0.22"
image.workspace = true
palette = "0.7"
resvg = "0.44"
schemars = { version = "0.8", optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tsify = { version = "0.5", optional = true }
twemoji-assets = { version = "1.5", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
