#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "../inc/iconutils.h"

// Generated by CMake
#include "version.h"

#include <QMainWindow>
#include <QStandardPaths>
#include <QDir>

#include <QMessageBox>

#include <QStringList>
#include <QStringListModel>
#include <QAbstractItemView>
#include <QFileDialog>
#include <QListWidget>


QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

    QList<QImage> defaultIcons;

private slots:
    void about();

    void on_addDirButton_clicked();

    void on_removeDirButton_clicked();

    void on_clearDirsButton_clicked();

private:
    Ui::MainWindow *ui;
    QItemSelectionModel* dirListSelectionModel;
    QAbstractItemModel* dirListItemModel;
};
#endif // MAINWINDOW_H
